"""Init for data types."""
from babelcode.data_types.command import Command
from babelcode.data_types.prediction import Prediction
from babelcode.data_types.question import IOPairError
from babelcode.data_types.question import Question
from babelcode.data_types.question import QuestionParsingError
from babelcode.data_types.question import QuestionValidationError
from babelcode.data_types.question import read_input_questions
from babelcode.data_types.result_types import ExecutionResult
from babelcode.data_types.result_types import PredictionOutcome
from babelcode.data_types.result_types import PredictionResult
from babelcode.data_types.result_types import QuestionResult
